// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7w5qj0aNrHoP8PrnGiL3soIvYSTNctU',
    appId: '1:501040465224:web:3e1688e3a17b5d5f5c1f7d',
    messagingSenderId: '501040465224',
    projectId: 'realeye-6739d',
    authDomain: 'realeye-6739d.firebaseapp.com',
    databaseURL: 'https://realeye-6739d-default-rtdb.firebaseio.com',
    storageBucket: 'realeye-6739d.firebasestorage.app',
    measurementId: 'G-E9ZVKMDJ0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcE7ubNny38ARibY2SoATHbAJGBUJRLBE',
    appId: '1:501040465224:android:da163d366b1dbd575c1f7d',
    messagingSenderId: '501040465224',
    projectId: 'realeye-6739d',
    databaseURL: 'https://realeye-6739d-default-rtdb.firebaseio.com',
    storageBucket: 'realeye-6739d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDotHdDETvGPg_GgL8vIsi7q4BEbUI6ts',
    appId: '1:501040465224:ios:6c296ba6dd8d1f955c1f7d',
    messagingSenderId: '501040465224',
    projectId: 'realeye-6739d',
    databaseURL: 'https://realeye-6739d-default-rtdb.firebaseio.com',
    storageBucket: 'realeye-6739d.firebasestorage.app',
    iosBundleId: 'com.example.realeyes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDotHdDETvGPg_GgL8vIsi7q4BEbUI6ts',
    appId: '1:501040465224:ios:6c296ba6dd8d1f955c1f7d',
    messagingSenderId: '501040465224',
    projectId: 'realeye-6739d',
    databaseURL: 'https://realeye-6739d-default-rtdb.firebaseio.com',
    storageBucket: 'realeye-6739d.firebasestorage.app',
    iosBundleId: 'com.example.realeyes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-7w5qj0aNrHoP8PrnGiL3soIvYSTNctU',
    appId: '1:501040465224:web:11759d2c7d550ed95c1f7d',
    messagingSenderId: '501040465224',
    projectId: 'realeye-6739d',
    authDomain: 'realeye-6739d.firebaseapp.com',
    databaseURL: 'https://realeye-6739d-default-rtdb.firebaseio.com',
    storageBucket: 'realeye-6739d.firebasestorage.app',
    measurementId: 'G-4YKWBFGMKZ',
  );
}
