import 'package:flutter/material.dart';
import 'package:navaveda/services/ai_service.dart'; // Import AI service

class BasicScreen extends StatefulWidget {
  final String language;

  BasicScreen({required this.language});

  @override
  _BasicScreenState createState() => _BasicScreenState();
}

class _BasicScreenState extends State<BasicScreen> {
  late List<String> questions;  // List of questions generated by AI
  final AIService _aiService = AIService(); // Instance of AIService
  bool _isLoading = false; // Flag to show loading indicator

  @override
  void initState() {
    super.initState();
    questions = [];
    _loadQuestions("basic"); // Default topic when screen is initialized
  }

  // Load questions from AI service based on the selected topic
  void _loadQuestions(String topic) async {
    setState(() {
      _isLoading = true; // Start loading
    });

    try {
      // Fetch questions from the backend API based on language and topic (e.g., 'basic')
      List<String> generatedQuestions = await _aiService.generateQuestions(widget.language, topic);

      setState(() {
        questions = generatedQuestions; // Update the questions list
      });
    } catch (e) {
      print("Error generating questions: $e");
      setState(() {
        // Fallback questions in case of failure
        questions = [
          'How to run ${widget.language}?',
          'What is the history of ${widget.language}?',
          'What are the basic concepts of ${widget.language}?',
        ];
      });
    } finally {
      setState(() {
        _isLoading = false; // Stop loading
      });
    }
  }

  // Method to get AI's answer to a question
  Future<void> _getAIAnswer(String question) async {
    setState(() {
      _isLoading = true; // Show loading indicator
    });

    try {
      // Fetch AI's answer to the question
      String answer = await _aiService.askQuestion(question, widget.language, 'basic');

      // Show dialog with answer
      showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('AI Answer'),
            content: Text(answer),
            actions: <Widget>[
              TextButton(
                child: Text('Close'),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ],
          );
        },
      );
    } catch (e) {
      print("Error fetching answer: $e");

      // Show error dialog if AI request fails
      showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('Error'),
            content: Text('Failed to get answer. Please try again later.'),
            actions: <Widget>[
              TextButton(
                child: Text('Close'),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ],
          );
        },
      );
    } finally {
      setState(() {
        _isLoading = false; // Hide loading indicator
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('${widget.language} Basics')),
      body: _isLoading
          ? Center(child: CircularProgressIndicator()) // Show loading while questions are being fetched
          : Column(
        children: [
          // Add buttons to select topic: basic, intermediate, or advanced
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                onPressed: () => _loadQuestions("basic"),
                child: Text('Basic'),
              ),
              SizedBox(width: 10),
              ElevatedButton(
                onPressed: () => _loadQuestions("intermediate"),
                child: Text('Intermediate'),
              ),
              SizedBox(width: 10),
              ElevatedButton(
                onPressed: () => _loadQuestions("advanced"),
                child: Text('Advanced'),
              ),
            ],
          ),

          // Display the list of questions
          Expanded(
            child: ListView.builder(
              itemCount: questions.length,
              itemBuilder: (context, index) {
                return ListTile(
                  title: Text(questions[index]),
                  onTap: () async {
                    // Get AI response when a question is selected
                    await _getAIAnswer(questions[index]);
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
